### ISSUE TITLE
Cannot set CloseAfterNoMessage for SignalR Core HubConnection's transport websocket

### ISSUE THREAD

**Issue by PWAvi** [Benedicht/BestHTTP-Issues#149]
Hi Benedicht,

We're using SignalR Core and noticed that there isn't a way for us to access the CloseAfterNoMessage option in WebSocketBaseImplementation through this pathway, so it's always hardcoded to the default `TimeSpan.FromSeconds(2);`. Do you have any recommendations on how we can change it currently? Or is this something you can expose as an option when creating a HubConnection in a future version?

Thanks,

Avi

**Comment by Benedicht** [comment]
`HubOptions` already has a `WebsocketOptions` property since v2.8.0, but now it can be used only to set ping invervals and extensions.
Is 2 seconds is too low or too high for you?

Also, since the new `WebsocketOptions`, the default setting/behavior is to disable websocket's ping mechanism as SignalR Core has its own.

**Comment by PWAvi** [comment]
Thanks for the reply! We're still on 2.7.0 so we'll try updating and seeing if we still notice an issue. 2s seemed too low for some cases but if it's using SignalR Core's ping over Websocket's it may be resolved for us. I'll close this for now and reopen if we run into problems again. Thanks!
