### ISSUE TITLE
Unneccessary Memory allocated

### ISSUE THREAD

**Issue by lymancao** [Benedicht/BestHTTP-Issues#169]
Our app download many files using BestHTTP (v2.5.4).
I noticed heap memory allocated for BufferedReadNetworkStream in TCPConnector (line 538).
The default value of ReceiveBufferSize may reach 8Mb for EACH THREAD.
```

if (Stream == null)
{
	bool isSecure = HTTPProtocolFactory.IsSecureProtocol(request.CurrentUri);

	// set the stream to Client.GetStream() so the proxy, if there's any can use it directly.
	this.Stream = this.TopmostStream = Client.GetStream();

	/*if (Stream.CanTimeout)
	    Stream.ReadTimeout = Stream.WriteTimeout = (int)Request.Timeout.TotalMilliseconds;*/

#if !BESTHTTP_DISABLE_PROXY
	if (request.HasProxy)
	{
	    try
	    {
	        request.Proxy.Connect(this.Stream, request);
	    }
	    finally
	    {
	        request.Timing.Add(TimingEventNames.Proxy_Negotiation);
	    }
	}

	if (request.IsCancellationRequested)
	    throw new Exception("IsCancellationRequested");

#endif
	// proxy connect is done, we can set the stream to a buffered one. HTTPProxy requires the raw NetworkStream for HTTPResponse's ReadUnknownSize!
	this.Stream = this.TopmostStream = new BufferedReadNetworkStream(Client.GetStream(), Math.Max(8 * 1024, HTTPManager.ReceiveBufferSize ?? Client.ReceiveBufferSize));


```
I am not sure why this.Steam is assigned twice, but I think that the memory allocated is not neccessary.

**Comment by Benedicht** [comment]
Stream is used in the proxy connection and in Close (if for some reason have to close the connection, it's already assigned while the connection is waiting for a proxy negotiation). Assigning it twice doesn't cause any problems.

**The default value of ReceiveBufferSize may reach 8Mb for EACH THREAD.**

I'm not sure i understand it correctly. `HTTPManager.ReceiveBufferSize` has no value by default, so it uses `Client.ReceiveBufferSize`, `Client.ReceiveBufferSize` returns with the socket's receive buffer size assigned by the kernel/driver. Never seen 8Mb of rcv buffer sizes before, but i guess it can happen.

You can maximize the size of the buffer by setting `HTTPManager.ReceiveBufferSize` to a value more acceptable by you.

**Comment by lymancao** [comment]
Our app doesn't use proxy, so I am not sure BufferedReadNetworkStream is neccessary.

**Socket's default receive buffer size can reach 8M on Android Mobile.**

**Comment by Benedicht** [comment]
`BufferedReadNetworkStream` isn't there because of proxy, but the double assignment. Also, the plugin can detect proxy settings on your client's device, so even if you doesn't use one, users might do.

`BufferedReadNetworkStream` is there to buffer client side reads. Sometime the plugin wants to read only a few bytes from the network, and that would mean it has to do a slow user-kernel transition. Instead it tries to fill up its buffer with one slow system call. This has two positive effect:

 1, now the system has (more) space in the TCP receive buffer, it can start to update network windows and receive data from the server
 2, faster processing of buffered data

The preferred way is to set the buffer size through `HTTPManager.ReceiveBufferSize`, but as you have all the source code, you can add/remove implement very different logic too.

**Comment by lymancao** [comment]
Thank you for your detailed explaination.

I will set `HTTPManager.ReceiveBufferSize` before use.
