### ISSUE TITLE
Exception "Cannot write application data on closed/failed TLS connection" is thrown by TlsProtocol.

### ISSUE THREAD

**Issue by feraligatr** [Benedicht/BestHTTP-Issues#212]
BestHTTP version: 3.0.11
Unity 2022.3.51f1
Platform: Android

In OverHTTP1.SendThread(), it doesn't check whether the connection is closed by server when writing data to stream. It causes the exception.
Although it doesn't affect functions, error outputs are not allowed in my project.

**Comment by Benedicht** [comment]
It would be hard to check, because the underlying system can decide the connection is broken between a check and the sending.
You can control the amount of logging of the plugin through the Logger'r log level, like this: `Best.HTTP.Shared.HTTPManager.Logger.Level = Best.HTTP.Shared.Logger.Loglevels.None;`.
