### ISSUE TITLE
request.Response.GetHeaderValues(string s) doesn't work correctly

### ISSUE THREAD

**Issue by dyhmichail** [Benedicht/BestHTTP-Issues#37]
Hello, I try to get header info from https request.responce
It must be something like key - "Content-Disposition", value - "attachment; filename="IMG_20200730_233442.jpg"
But after 
```
                foreach (var head in request.Response.Headers)
                {
                    Debug.Log(head.Key.ToString() + ": " + request.Response.GetHeaderValues(head.Key.ToString())); 
                }
```
I've got "content-disposition: System.Collections.Generic.List`1[System.String]"

**Comment by Benedicht** [comment]
As its name suggests (GetHeaderValue**s**) it returns with a list of values. The list might contain only one element (most of the time), but, because one header can be included multiple times in a response it's a valid use-case to have multiple values for one header.
The best example is with cookies! The server can send multiple set-cookies header:

> **set-cookie**: 1P_JAR=2020-09-10-19; expires=Sat, 10-Oct-2020 19:06:51 GMT; path=/; 
> **set-cookie**: SIDCC=AJi4QfGmAD4y; expires=Fri, 10-Sep-2021 19:06:51 GMT; path=/; domain=.google.com; priority=high
> **set-cookie**: __Secure-3PSIDCC=AJi; expires=Fri, 10-Sep-2021 19:06:51 GMT; path=/; domain=.google.com; Secure; HttpOnly; priority=high; SameSite=none

That's one key (set-cookie) with multiple values!

If your heder should appear only once, you can use the `GetFirstHeaderValue` function to return the list's first element.
