### ISSUE TITLE
Exception: An unexpected error occurred during connection handshake

### ISSUE THREAD

**Issue by BradMclain** [Benedicht/BestHTTP-Issues#50]
I am getting `An unexpected error occurred during connection handshake` exception when trying to connect to a signalr server.

The same server works fine when connecting via web using chrome/firefox and using the official library signalr client from a C# script. It also works fine from unity using Best HTTP when connecting to the same server run locally from visual studio.

The deployed server is proxying using apache through to a kestrel service on ubuntu.

[besthttp.log](https://github.com/Benedicht/BestHTTP-Issues/files/5871315/besthttp.log)

**Comment by Benedicht** [comment]
The first issue is that the server advertising the websocket transport, however when the client tries to connect with itm it just returns with a status code of 200. This is an issue of the server.

The client has a bug too, as it's stuck in its initial state.

A good workaround would be to check out the server what's wrong with the websocket transport.

**Comment by Benedicht** [comment]
> The client has a bug too, as it's stuck in its initial state.

This might had an early statement. It seems that the plugin wasn't stuck. After the failed websocket connect the plugin tries to connect with the next available one, the long polling transport. 
The first request was the connect request with the choosen protocol (json). The second one was a general poll request, but the server expected to send back an empty json object ({}), but instead the server sent back an error the "An unexpected error occurred during connection handshake" one.

**Comment by BradMclain** [comment]
Do you have any idea what might be going wrong given I can successfully connect using `Microsoft.AspNetCore.SignalR.Client` in a different program?

**Comment by Benedicht** [comment]
Tried to replace this issue by deploying my demo page on linux and routing the request through a proxy to block the webscket request. This way i couldn't replicate it, however this could be because the websocket request never reached the web app.

What could be helpful at this point:

1. a minimal repro project and/or
2. a capture of a proxy session that connects and one that doesn't. For these captures i can recommend [Charles Proxy](https://www.charlesproxy.com). You can let the plugin use it by adding this line somewhere in your startup code: `HTTPManager.Proxy = new HTTPProxy(new Uri("http://localhost:8888"), null, true);`
